name: build-test

on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest]
        lazarus-versions: [1.6.4]
    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v2.2.6
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        include-packages: "Synapse 40.1"
    - name: Build the Main Application
      run: |
        set path=%LAZARUS_DIR%;%LAZARUS_DIR%\fpc\3.0.4\bin\i386-win32;%path%
        lazbuild "transgui.lpi"        
    - uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: D:\a\transgui\transgui\units\transgui.exe
